version: "3.7"

services:

  mongo-node-1:
    image: mongo:7.0.5
    container_name: mongo-node-1
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./logs:/var/log/mongodb
      - ./mongodb-keyfile.key:/etc/mongodb-keyfile.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: bobby
      MONGO_INITDB_ROOT_PASSWORD: bobby
      MONGO_INITDB_REPLICA_SET_NAME: artist-saas-set
      MONGO_INITDB_DATABASE: admin
    command:
      - /bin/sh
      - -c
      - |
        chmod 400 /etc/mongodb-keyfile.key
        chown 999:999 /etc/mongodb-keyfile.key
        mongod --replSet artist-saas-set --bind_ip_all --auth --keyFile /etc/mongodb-keyfile.key
    networks:
      - artist-saas-net

networks:
  artist-saas-net:
    driver: bridge
    name: artist-saas-net